_extends: .github
repository:
  name: repository-settings
  description: >-
    form8ion plugin for managing configuration for the repository-settings app
    for a project
  homepage: https://npm.im/@form8ion/repository-settings
  private: false
