root: true

extends:
  - '@form8ion'
  - '@form8ion/vitest'
  - '@form8ion/cucumber'


rules:
  import/extensions:
    - error
    - ignorePackages
  import/no-unresolved:
    - error
    - ignore:
      - '@octokit/core'
      - 'vitest-when'
